### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by CerealKillerSG** [parabola949/Werewolf#105]
A multiple of suggestions. They can be used together or separately.

The first suggestion, Im sure has been proposed before.
Basically to extend the game to 50 players max. This of course can be adjusted by the admins.
Of course, it is not just to allow more players, but also include more roles and themes.

Basically, a 50 player game is moving from chaos mode to a new, "Crisis Mode"
In this story line, the national government has acknowledge the growing problem and has sent numerous professionals to deal with the troubles arising in the town.

So far the game as not clear factions, but "sides"
Good: Villagers
Bad: Werewolf, Serial Killer
Ugly: Tanner
Weird: Cultists

------------------------------------------------------------------------------------------------------------------

One of the new "sides" is the "Enforces" side. Government forces sent in by the Dictator to regain control of the town. They may seem like a "neutral force", but they have their own agenda.
Roles:
Soldier (Crossed Swords Emoji)
Sailor (Anchor Emoji)
Policeman ( Man in blue uniform emoji)
Spy (Mysterious man in coat and hat emoji)
Demoman (Bomb emoji)

Their objective is to get one other faction to win. Once that happens it is considered the peace has been brought upon the town, whichever that group is(even tanner). However, at the same time, at least 4 "Enforcers" must be alive for them to win. Enforcers will not know who each other are, but will know who their fellow Enforcers pick for the night actions.

Role details:
Soldier (Crossed Swords Emoji)*
Pick a player to protect(similar to GA).
If a villager is picked and attacked/converted, Soldier kills whoever is attacking/converting.
If villager is not attacked/converted, nothing happens.
If a cultist or zombie is picked, Soldier is converted.
If a WW or SK is picked, Soldier kills them instead.

Sailor (Anchor Emoji)*
Pick a player to ship out(similar to GA).
If a villager is picked and attacked/converted, whoever is attacking/converting drowns.
If villager is not attacked/converted, nothing happens.
If a cultist or zombie is picked, Sailor is converted.
If a WW or SK is picked, Sailor kills them instead.

*Basically the same role, BUT they will not know who each other and to remove confusion.
Their 'protection' ability can last up to 5 times. If they pick a villager and nothing happens, it is no part of the 5 times. So this 5 times is only if the villager is really protected.
For being converted, also requires 5 times (belief too strong/20% chance)
If wolves attack them, it also require a total of 5 times.
Basically these 2 are slightly OP villagers.
However the Serial Killer can kill them in 1 try.
If they pick the Enforces, it will be like a villager.
However if either the Soldier and Sailor pick one another, the person who is chosen cannot use his night actions.

Policeman (Man in blue uniform emoji)
Similar to the Soldier and Sailor, with minor differences.
Every night the Policeman picks 1 person to arrest and throw into prison.
That person cannot use his night actions. However the next day, the person cannot by lynch and cannot vote to lynch. This include the Soldier and Sailor.
Whoever is chosen by the Policeman will not be affecting the Policeman.
However if the wolves attack, the cultists or zombies try to convert, it will require 5 tries.
The Serial Killer however can kill them in 1 try.

Spy (Mysterious man in coat and hat emoji)
Similar to the detective/seer. However he will see which faction the member belongs to. Serial Killer will be seen as a villager. Likewise with his fellow Enforces, he will take 5 times to be converted/attacked for it to take effect. However for Serial Killer it would still need only 1 try.

Demoman (Bomb emoji)
Similar to tanner, he does not have night options. And his objective is to get lynched.
Once he is lynched, he blows up the entire town, saving his (surviving) enforces, but himself dying.
Similar to the rest of the enforces, it takes 5 attempts to convert/attack him, except for Serial Killer which only require 1.

Reasoning: The Enforcers require more attempts to convert or attack because of their training they are mentally and physically stronger. However because the Serial Killer is crazy enough, to even disregard his own life, he is able to kill them as he goes all out. 
This is the catch: If a specific Serial Killer attacks each Enforcer, he will die after killing the 5th one as he is too worn out from the fights.

------------------------------------------------------------------------------------------------------------------
Another faction to be introduced: "Zombies"
As a counter balance to the cult, the game will start with 1 Zombie who will start converting people.
However, here are some differences from cult:
Zombie can convert WW. Once converted, WW will become Zombie and no longer WW.
If Zombie attempt to convert any villager, the villager will die. One Zombie will die.
If Zombie attempt to convert Serial Killer, Zombie will die.
If Zombie attempt to convert a Cultist, Cultist will die.
Zombies would fall under the "Weird Category"
If Werewolves chose to eat a Zombie, Zombie will die, one of the Werewolves becomes a Zombie.
If Cultist attempt to convert a Zombie, Zombie will be converted to cult, one Cultist will be zombie.

Of course, with this bring a new role:
Zombie Hunter. Same as Cultist Hunter, except for Zombies.

------------------------------------------------------------------------------------------------------------------

Some changes to Wolf Factions to help balance the game.
Roles:
Alpha Wolf (additional A emoji)
Beta Wolf (additional B emoji)
Omega Wolf (additional O emoji)

Wolves will not know who other wolfs are. Except for 1 of them, the Alpha Wolf.
However Alpha wolf does not vote who to eat.
Beta wolf is basically the second in command who becomes the Alpha wolf if the Alpha wolf dies.
Only 1 Alpha and Beta Wolf.
The other wolves will also not know who are the alpha, beta or omega wolves.

The Omega Wolf is the "traitor" of the wolves. If he is the remaining wolf, he will be converted to a villager.

The Seer will only see them as wolves, but the detective can know their specific roles.

------------------------------------------------------------------------------------------------------------------

Basically like the wolves and the enforcers, the cultist and zombies will have 2 new roles:
Cultist Leader
Chief Zombie

Basically, they are like the Alpha Wolf. Only they will know who is in their respective factions but will not get to vote who to convert every night. The rest of the Zombies and Cultists will not know each other.

However, if they die, the next cultist or zombie that was chosen after them will become the Cultist Leader and Chief Zombie. This is NOT like the Wolf were it is only limited to Alpha and Beta.

------------------------------------------------------------------------------------------------------------------

Of course, with all these changes, the Villagers should also get some assistance.
2 new roles:
Psychiatrist 
Doctor (Caduceus emoji)

The Psychiatrist chooses one player to "help" every day.
If the Serial Killer is chosen, he will become a lowly villager, but the Psychiatrist will die.
If a villager is chosen, he has 40% chance of becoming a Serial Killer or cultist by going crazy.
If a wolf is chosen,  the Psychiatrist will die.
If a cultist is chosen, the cultist will become a lowly villager.
If a zombie is chosen, the Psychiatrist will become a zombie.
If the cultist try to convert the Psychiatrist however, one cultist will become their previous role.
If the Cult Leader, try to convert the Psychiatrist, he will die.
If the zombie try to convert the Psychiatrist, the Psychiatrist will become a zombie.
If the wolfs try to eat the Psychiatrist, the Psychiatrist will die.
If the Serial Killer try to kill the Psychiatrist, he will come a lowly villager.
If the Psychiatrist try to help a Enforcer, it is minus one conversion attempt by cultist.

The Doctor chooses one player to "cure" every day.
If a Wolf is chosen, the wolf becomes a villager, but the doctor dies.
If a the alpha or beta wolf is chosen, they become an omega wolf and the doctor does not die.
If a villager is chosen, he becomes a werewolf.
If a cultist is chosen, he becomes a zombie.
If a the Serial Killer is chosen, the Doctor will die.
If a zombie is chosen, he will become a villager.
If the Serial Killer chose to kill the doctor, the doctor will die.
If the wolf try to eat the doctor, one wolf will become a villager.
If the zombie try to convert the doctor however, one cultist will become their previous role.
If the Chief Zombie, try to convert the doctor, he will die.
If the Doctor try to help a Enforcer, it is minus one conversion attempt by zombie.

Another separate one is that for the gunner(which can be used together with the above suggestions)
The number of bullet and exposing of the gunner can be modified a little.
If the game is still limited to 35:
5-15 players: 1 bullet (Gunner exposed)
16-25 players: 2 bullets (Gunner exposed 1st bullet)
26-35 players: 3 bullets (Gunner exposed 2nd bullet)
If the game is increased to 50(with or without the above suggestions)
36-45 players: 4 bullets (Gunner exposed 3rd bullet)
46-50 players: 5 bullets (Gunner exposed 4th bullet)

------------------------------------------------------------------------------------------------------------------

Basically, the idea is to allow people to play a more inclusive and dynamic round.
As roles are more dynamic, there is more chances of "changing" roles throughout the game.
This will help those players who die very early from being demoralized and waiting very long for next round.
Also, it will discourage people to do less "random" choices and actually pay attention to the conversations. At the same time, those who are too quiet will be required to participate more.

Of course, there are pros and cons to everything, including these suggestions. Just my ideas that I wanted to recommend. Maybe the ideas may not be implemented but could spark thoughts for other ideas.

Either ways, thanks for your time. The game is really wonder and thanks for developing it, maintaining it, and most important letting us play for free. Many of us really appreciate it.

**Comment by Aidil02** [comment]
PLS ALLOW THIS TO HAPPEN. I LOVE THIS SUGGESTION

**Comment by CloneMMDDCVII** [comment]
@Aidil02 Well. To begin with, allowing 50 players in game is not yet near planned. Why ? Might you ask.
Well, 35 players games are already :
-a heavy load on the bot
-rarely reached
-insanely long and complex

So 50 p games are not really interesting for us. 

Now regarding new roles, they all are iteresting, seem pretty balanced, but again there are issues :
-it's long to create new roles. The dev has a life. And saying that werewolf is time consuming would be close to defining "understatement".
-the ratio SatisfactionMoneyAndReward/TimeAllocatedToWerewolf tends towards zero. Maybe even less.
-Para codes ww by himself. The only help he has is on administration and sometimes bug fixes. And time to spend is not something he has right now.

Of course, a solution would be monetizing werwolf, but how ? Werewolf is user friendly. You can't put ads all the time. You can't really make it a paid game either. Then how about donations ? Well, to put it simply, the only ones donating are main and global admins.

So even so your ideas are very interesting, i am afraid we can't actually put them into place for now.

**Comment by CerealKillerSG** [comment]
No worries, fully understand. Just thought Id put it out there! Thanks for your time though!

**Comment by CloneMMDDCVII** [comment]
@CerealKillerSG Feel free to donate to help para to create more feature. Even 1 dollar helps. Really ;)

**Comment by parabola949** [comment]
@CerealKillerSG I like some of the roles.  I do plan to add more soonish, but right now stability is high priority.  As for 50 player game - 35 players is already just too insane, too much to keep up with for a chat game.  50 players would be nearly impossible to handle from a psychological perspective for the players.  I've actually already had many complaints that 35 is too much.

Again though - I like some of these roles.  Chances are pretty high I'm going to use some.  For now though, closing this issue.

**Comment by CerealKillerSG** [comment]
Ah ok I see I see. Well true sometimes in certain groups 35 player games get rather overwhelming haha.

Thanks for reading the comment!
