### ISSUE TITLE
[Suggestion] Lynch Abuse 

### ISSUE THREAD

**Issue by JorgeDDW** [parabola949/Werewolf#109]
Hi there team, 

I have an idea for those in group that get kills a lot like my self because of people not thinking about.

My idea is to create a way for that people when the lynch raking is more than 50% of all the others in the group of playing that one get the Tanner Role.

What do you think?

**Comment by CloneMMDDCVII** [comment]
@JorgeDDW nope. People like me would win their everygame :p

**Comment by parabola949** [comment]
A few things:
- If this was changed, then people would catch on, and assume that player was Tanner
- The amount of CPU it would take to search the database for lynch rating would be insane, especially during peak time with 5000+ players at a time
