### ISSUE TITLE
Betabot access request

### ISSUE THREAD

**Issue by shellals** [parabola949/Werewolf#113]
Hi Para.

About the group
Werewolf Addict - has been active since the past two months and has been having a steady growth in members plus the members are quite active. 

Request
We would like the opportunity to lend a hand to the development team by being a part of the testing of betabot. 
The group moderated by us - the admins would report any bug, shutdown, or likewise unexpected issue. 

Thanks for your consideration. :) 

Regards

**Comment by dllz** [comment]
@shellals I am under correction but we are not taking any applications for beta bot right now as the beta program has been shut down.

**Comment by shellals** [comment]
@dllz ugh, really? Alright then. Thanks Daniel. :)
