### ISSUE TITLE
/config language bug

### ISSUE THREAD

**Issue by jack980517** [parabola949/Werewolf#114]
Note: the personal language and group language should be different in order to find this problem.
My personal language is Cantonese while the group language is Simplified Chinese.
Steps:
/config
Bot PM: "你想做咩啊？" ("What do you want to do" in Cantonese)
Change Language
Bot PM; "选择一种语言变体。" ("Choose a language variant" in Simplified Chinese)

And all messages afterwards are in Simplified Chinese, including the next "What do you want to do" when returning to the main menu after changing the language. My speculation is that the messages after the first one are set to use the group language instead of the personal language. I don't really care about which should be the "right choice", but this inconsistency needs to be fixed.

**Comment by renyhp** [comment]
@jack980517 I will fix this

**Comment by jack980517** [comment]
I've found the line of code setting the language of the messages, and it seems that this fix requires more than changing one line of code... I've thought about getting the developer achievement with this but now I gave up lol

**Comment by parabola949** [comment]
@jack980517 Easy fix, give me just a moment :P
