### ISSUE TITLE
New roles

### ISSUE THREAD

**Issue by nzibn** [parabola949/Werewolf#115]
Hey para.

I want to give suggestion,how about we change from serial killer to grim reaper..that will be a major update..thanks para!!

**Comment by dllz** [comment]
@nzibn I am not sure if you are being sarcastic or not...

**Comment by nzibn** [comment]
@dllz what do you mean by sarcastic??

**Comment by dllz** [comment]
@nzibn I just do not understand what would make it a major update?

**Comment by nzibn** [comment]
@dllz i just said it..but please make it happen!!

**Comment by nzibn** [comment]
@dllz sorry for the exclaimination mark...

**Comment by parabola949** [comment]
@nzibn Just so everyone knows, as I have gotten MANY questions about this - 
There will be NO new roles for awhile, not until I have completely revamped the role assignment system.

The current method of "at x players, add y role" has reached the point that the only way to get new roles is to play in a large group (or chaos).  The new system will instead assign a point value to each role, and create teams using those values to balance the teams.  This way, you can play a normal game, but with various roles - and it will always be balanced.

Until this has happened, there will be no consideration of any new roles.

**Comment by nzibn** [comment]
@dllz well thanks for the info...
