### ISSUE TITLE
[Bug?] GA Guarded CH, pm notified CH the guard, but announces CH dead in group while player list shows alive

### ISSUE THREAD

**Issue by jeffchoy94610** [parabola949/Werewolf#117]
Group: Werewuff Main
Bot used: Beta Bot
Time of game starting: 19 Sept 2016 04:53 (GMT+8)
Time of issue occurring; 19 Sept 2016 04:59 (GMT+8)
Time of game ending: 19 Sept 2016 05:11 (GMT+8)

Bot announces in group of 'CH Dead':
`It seemed a quiet enough night for Alessandra Ambrosio (http://telegram.me/Sepcya), but they were wrong.  The villagers gather in the morning to find Alessandra Ambrosio (http://telegram.me/Sepcya) split from head to toe, but oddly the liver was missing...  The serial killer has struck again! the Cultist Hunter 💂 is dead`

Followed by (CH Alive):

> Players Alive: 9/15
Aguapanelo (BOG.co) (http://telegram.me/Aguapanelo): 💀 Dead - the Detective 🕵
J O K E R (http://telegram.me/Adrnsml): 💀 Dead - the Fool 🃏
J J 👼 (http://telegram.me/jjw91): 💀 Dead - the Hunter 🎯
Razi Irfan (http://telegram.me/Terrorrazi): 💀 Dead - the Cursed 😾
Hari Ertanto (http://telegram.me/xunx747): 💀 Dead - a Mason 👷
Dhewa Tanaka: 💀 Dead - a Cultist 👤
Alessandra Ambrosio (http://telegram.me/Sepcya): 🙂 Alive
Jeff (http://telegram.me/jeffffc): 🙂 Alive
iyang (http://telegram.me/gyxxs): 🙂 Alive
ĎÔŇ ŤŘÎŠŤÂŇ ŶÔŁÔŠŴÂĞ (http://telegram.me/deladela): 🙂 Alive
kaykay (http://telegram.me/kxykay): 🙂 Alive
Sherry (http://telegram.me/rhafmie): 🙂 Alive
Wendy Putra (http://telegram.me/wputra): 🙂 Alive
Isa FVCKOFF (http://telegram.me/Isa_izzudin_r): 🙂 Alive
JM: 🙂 Alive

I asked the CH (Alessandra Ambrosio), she did receive PM from bot saying GA has guarded her that night. And she stills succeeded continue playing the game.

![](http://puu.sh/rfSo7/85331abd94.png)

**Comment by jeffchoy94610** [comment]
Another group encountered the same issue.
Bot used: Bot 2
Time: 23 Sept 2016 ~12:00 (GMT-3)
Group ID: -1001052914751

![screen shot 2016-09-24 at 00 43 32](https://cloud.githubusercontent.com/assets/15724935/18794025/22c73b3a-81f0-11e6-9232-1c7768a1c8b0.png)

Confirmed GA guarding the CH, and CH did receive PM from bot about the guard.

(Reference: search Support group for "#117")

**Comment by renyhp** [comment]
This is tricky but I get why that happens. If I'm right, this happens only when CH chooses SK. I'm gonna fix it in the less clean way, but I plan to redo all the death in-group notification part so that this kind of bugs shouldn't happen anymore... if @parabola949 is okay with that.
