### ISSUE TITLE
Traitor description unclear

### ISSUE THREAD

**Issue by jack980517** [parabola949/Werewolf#118]
The role description states that the seer **may** see the traitor as werewolf, but doesn't say anything about the other possibilities, and some people (including me) understood it as that the seer may see the traitor as werewolf or traitor. But the real situation is villager or werewolf. This could cause serious problems, as I just encountered such situation, thought I was a fool, and fled the game only to find I'm seer.

**Comment by parabola949** [comment]
@jack980517 I am going to point out, it's people like you that are the reason we allow admins to disable fleeing.  Fleeing was intended for "I gotta go, something came up", not "oh I don't like my role, screw this".  That ruins the game for other players.  If you are the fool, you pretend to be the seer for the actual seer.  You still work with your team.  Running away only hurts your team.

**Comment by jack980517** [comment]
In our group we don't play as fools like this. When somebody found that he/she is a fool, he/she would tell it publicly in the group to avoid misleading other people, and be a useless role ever since. I flee not because I don't like the role, but because I don't think a fool matters in a game. That's how games in our group are played, at least.

**Comment by parabola949** [comment]
@jack980517 Then your group needs to learn strategy.  Thats not how you play the fool.

**Comment by jack980517** [comment]
If fools are played like this, good roles would be misled, which would cause bad results. The only way I see to avoid this is PMing between every good role, which ruins the game in my opinion.

**Comment by dllz** [comment]
@jack980517 So does fleeing when you are fool. You are ruining the game

**Comment by jack980517** [comment]
I'm NOT because staying in the game would DO NOTHING in our play style.
Regardless of what happened because of the unclear description, it itself is still an issue. You shouldn't ignore it just because you think my play style is wrong.
Besides, multiple play styles are possible under one single set of rules. There are no right or wrong play styles, only suitable and unsuitable ones for every individual.
That's all I'm gonna say. Further discussion would not yield any results IMO.

**Comment by CloneMMDDCVII** [comment]
@jack980517 i will change and update the description...
thanks for pointing it out.

however, as para and daniel said, fleeing is just a jerk like attitude. if you don't want to mislead people. then just tell openly you are fool. and increase village's votepower.
