### ISSUE TITLE
New role suggestions

### ISSUE THREAD

**Issue by michelleized** [parabola949/Werewolf#120]
Wolf Cub (Team WW) - if he/she dies, the werewolves get two kills the following night. If the seer finds a wolf cub, he/she will appear as werewolf (not a cub). 

Old Hag (Team VG) - At night, this player will indicate who must leave the village the next day. It can be from team vg o ww. 

The Count (Team VG) - At the first night, he/she is told how many werewolves are present in the game.

Lycan (Team VG) - He/she is a villager, but the lycan appears falsely to be a werewolf to the Seer.

Sorcerer (Team WW) - the seer counterpart of the werewolves. He/she only knows if he/she has found a werewolf or another seer.

Hoodlum (Neutral) - separate from other teams. He/she will indicate two players on the first night. If they die and the hoodlum is alive at the end of the game, he/she wins no matter what team wins.

Nostradamus (Team VG) - He/she will predict the winning team on the 1st night. If that team wins AND he/she is alive at the end of the game, he/she gets a solo win. For the rest of the game he/she is a villager.

*\* Translated and uploaded on behalf of players from FIlipino group. (userid: 266779820)

**Comment by CerealKillerSG** [comment]
Nice ideas. Wolf Cub shouldnt be able to eat though
