### ISSUE TITLE
[sugestion] please return sk role to what it used to be 

### ISSUE THREAD

**Issue by stefstefdr** [parabola949/Werewolf#121]
Suggestion from players :
Please decrease the chance of SK being eaten by wolf from 50% to 25%, or even more back like the first time (0%)

Now SK is not powerful and SK is alone, so if SK easily can be eaten by wolf, it makes SK even weaker. It become boring role like vgs. Please take our advice. Thanks.

**Comment by parabola949** [comment]
@renyhp this one should be simple enough, want to handle it?
