### ISSUE TITLE
Decrease the chance of SK being eaten by wolf

### ISSUE THREAD

**Issue by taletaletale** [parabola949/Werewolf#122]
I've received suggestion from ww players hoping that dev would decrease the chance of SK being eaten by wolf from 50% to 25%, or even more back like the first time (0%)

Some of them says now SK is not powerful and SK is alone, so if SK can easily be eaten by wolf, it makes SK even weaker.

**Comment by renyhp** [comment]
Please read other issues before posting another one. This is exactly identical to the previous one (#121). Closing this
