### ISSUE TITLE
BrokenClock's To do List.

### ISSUE THREAD

**Issue by CloneMMDDCVII** [parabola949/Werewolf#123]
1) even if we keep 35p as an option, default max should be between 25 and 30. 35 is way too big for player interractions.
2) We DO need to rework that role assignation algortihm. Because standard is boring, and chaos is.. well, it's not meant to be the standard way of playing. and it's a complete mess.

**Comment by CloneMMDDCVII** [comment]
@CloneMMDDCVII edited, removed 3

**Comment by CloneMMDDCVII** [comment]
@CloneMMDDCVII 3) reorganise lang files (they are a mess) (waits to get lynched)

**Comment by renyhp** [comment]
Can I close this one? Point 2 is solved. Maybe you can reopen an issue with Point 1, and if Para approves he will change it (or I will). With point 3, you should maybe elaborate a bit, but still, in another separate issue, maybe.
