### ISSUE TITLE
SK dies when WW kill them

### ISSUE THREAD

**Issue by keynesfariz** [parabola949/Werewolf#127]
As the serial killer, you can kill ANYONE - wolves, hunters, gunners, guardian angels, whatever. If the wolves try to attack you, you will kill one of them (random), and live.

Serial killer dies when attacked by werewolves. The rule on the website says so.

**Comment by keynesfariz** [comment]
I mean my theres an error in the werewolfiibot: my serial killer died by werewolf

**Comment by renyhp** [comment]
It is not an error in the bot, but an error on the website, or rather, the website isn't up to date. Lately, we made so that, if the WWs attack the SK, the SK has 20% chance to die, and 80% chance to kill a random WW. See #121, and commits 56cee6b and 5a9eb38.
