### ISSUE TITLE
Cult Hunter kills Cultist, but Cultist saved by GA

### ISSUE THREAD

**Issue by RainRat** [parabola949/Werewolf#129]
In a game I was in, I was informed by the bot that I had killed a cultist, but they were still alive.

I don't know exactly what happened, but the person thanked the GA. I assume they were visited by CH, GA, and (wolf or serial killer).

Main English group, 6:37pm, Oct 2nd

**Comment by renyhp** [comment]
Should be fixed by #125. Please post another issue if that happens again.
