### ISSUE TITLE
bot only sends you a message when eaten

### ISSUE THREAD

**Issue by eagle3000** [parabola949/Werewolf#13]
the bot lets you know when you are eaten by the wolves. it doesn't tell you when you die because you're killed by the SK, out of sorrow, because you visited the wrong house as a harlot, are shot, are lynched etc.
the bot should also send you a message when these events happen and you die

**Comment by parabola949** [comment]
These will be added soon

**Comment by parabola949** [comment]
After much discussion, this will not be added, as it will bring the bot closer to reaching API limits.
