### ISSUE TITLE
Final round bug

### ISSUE THREAD

**Issue by FernandoTBarros** [parabola949/Werewolf#132]
We were playing a normal game with 8 players.
In the second night, the wolf ate the drunk. And then left two players, the wolf and the cursed.
The game goes on, passes the voting, and just finished after the next action of the wolf, who was eat the cursed.
We thought that is a bug, the game was not to end after the wolf eat the drunk?

**Comment by renyhp** [comment]
This bug is already known and already fixed, ee #126, #119, #104, and commit 4a956815ed7da4506501069feb159839e43f9761. Beta bot has been rebuilt and currently has this error fixed. Bots 1 & 2 will be updated soon.

**Comment by FernandoTBarros** [comment]
Oh great! Sorry, I've looked into the open issues to find some related but didn't remember to look into the closed ones. Great work with the bot!
