### ISSUE TITLE
Automatically group Cults, Wuffs and Masons in a chat from which they are removed automatically after dying.

### ISSUE THREAD

**Issue by thecyclone** [parabola949/Werewolf#136]
This would enable better communication between the teams and there will be no need to PM several people the same thing. :(

**Comment by CloneMMDDCVII** [comment]
@thecyclone This is not possible because bots cannot create groups, nor delete them.Moreover, this would be a wreck if each game started a chat for each faction. It is up to you to try and talk with your team :)

**Comment by thecyclone** [comment]
@CloneMMDDCVII  3 groups: Wuffs, Masons, Cult can be manually created. The bots can automatically add people and remove them.

**Comment by ambravl** [comment]
@thecyclone I don't think they can add people, and your suggestion would mean there's a single group for all wolves/masons/cultists in werewolf... that would be chaos, considering the number of simultaneous games there are at any given time

**Comment by CloneMMDDCVII** [comment]
@thecyclone Nope. API does not allow that.
See telegram's website for more details on the bot API

**Comment by thecyclone** [comment]
@CloneMMDDCVII Then how are the bots able to kick people for flooding?

**Comment by ambravl** [comment]
@thecyclone They are able to kick and ban people from groups, but not add them. That's to avoid spam by bots.

**Comment by thecyclone** [comment]
@ambravl makes sense. Sorry for wasting your time. Thanks :)

**Comment by ambravl** [comment]
@thecyclone No problem, it's always good to see new suggestions! Thank you for thinking of ways to improve the bot and keep wuffing!
