### ISSUE TITLE
make a medium for deadtalk

### ISSUE THREAD

**Issue by myrs14** [parabola949/Werewolf#138]
Sometimes its anoyying when the dead one is still talk and giving so much clue. Why not give a medium role instead so the dead one can talk and giving a clue to the medium, the medium job is to tell the others what the dead is talking

**Comment by dllz** [comment]
@myrs14 How is this any different to the dead person talking. Except now it would be allowed...

**Comment by renyhp** [comment]
@myrs14 We will take this in account. However, note that this role can't be simply dealt with by the bot: if roles are secret while alive, that would mean everyone can say to be the medium and talk to the dead. Nevertheless, the bot can't understand the messages, so it's a role that would not have any interaction with the bot, and would maybe require the presence of an admin to delete the messages.
Anyway, this suggestion was already submitted somewhere, so I'll close this issue.

**Comment by myrs14** [comment]
I mean like town of salem game the dead talk can't be seen by live player. The dealtalk can pnly be seen by a medium at night and another dead player
