### ISSUE TITLE
Make a new thief role

### ISSUE THREAD

**Issue by myrs14** [parabola949/Werewolf#139]
Can you make a new role for thief. This role can switch role with other player at night and got that role for the rest of the game until she/he got switch again. The one who got switch will be the next thief.

**Comment by pjessica** [comment]
Wow thief role sounds interesting. Can I add my idea? I think its better if the thief can only steal once at the beginning of the game. The person who get stolen will become a villager and he/she doesn't know who stole his/her role.

**Comment by myrs14** [comment]
That's sound good too. The thief role is to make the game in chaos. Imagine when a thief stole warewolf role and after that the next thief stole sk role.

**Comment by myrs14** [comment]
That's sound good too. The thief role is to make the game in chaos. Imagine when a thief stole warewolf role and after that the next thief stole sk role.

**Comment by dllz** [comment]
@myrs14 we are trying to make the game more balanced right now so it is unlikely to appear unless you can suggest how it balances the game?

**Comment by joshkurien** [comment]
well, if a random role is being stolen (only on night 1) and the other person becomes a villager, then there is really only an equivalent of a villager added. Is there any question of balance/imbalance?

**Comment by dllz** [comment]
@joshkurien Yes because if I am a wolf and I know all the other wolves and my role is stolen I can tell everyone who the wolves are thus the role provides to much favour to the villagers
