### ISSUE TITLE
Game unresolved if the last two players one of them is sorcerer

### ISSUE THREAD

**Issue by kabag** [parabola949/Werewolf#142]
Cannot finish the game, because each keep lynched each other.

**Comment by dllz** [comment]
@kabag What roles where left

**Comment by kabag** [comment]
@dllz seer and sorcerer.

**Comment by renyhp** [comment]
@kabag Should be solved with my last commit. We'll wait for the bot to be updated

**Comment by renyhp** [comment]
Is this solved?

**Comment by kabag** [comment]
I don't know yet.never have the same situation again.

**Comment by renyhp** [comment]
I'm closing this one. Please reopen an issue if you encounter the bug again.
