### ISSUE TITLE
If the WildChild, Doppleganger, or Cupid doesn't choose the first night, bot should pick randomly

### ISSUE THREAD

**Issue by RainRat** [parabola949/Werewolf#15]
If the WildChild, Doppleganger, or Cupid doesn't choose the first night, bot should pick randomly.

It removes some of the strategy if the player can just choose not to choose.

**Comment by parabola949** [comment]
I'd prefer this be a configurable option.  In reality, if someone joins the game, is DG, and doesn't choose - that's on them.
