### ISSUE TITLE
Hunter Killing WW message doesnt send to group

### ISSUE THREAD

**Issue by BlaQPhoeniX** [parabola949/Werewolf#150]
When a wolf dies from trying to eat the hunter, the death message isn't sent to the group at all.

**Comment by MatteoIlGrande** [comment]
@BlaQPhoeniX I confirm, this happened to other places too..
Looks like the strings HunterShotWolf and HunterShotWolfMulti are somehow bugged...

**Comment by renyhp** [comment]
Was the wolf a Wolf Cub or an Alpha Wolf?

**Comment by BlaQPhoeniX** [comment]
@renyhp Alpha Wolf both times it happened.
