### ISSUE TITLE
Cases when wolves chose but didn't eat

### ISSUE THREAD

**Issue by renyhp** [parabola949/Werewolf#162]
We received reports of games where the wolves got an eat prompt, chose, but didn't eat.

1. The alpha wolf bit a mason, but the mason has been lynched before transforming. Since then, all wolf cannot eat anyone.

2. Wolf cub dies, wolves get two kills, but after those are never again able to eat/kill again... no blacksmith, drunk wasn't attacked, GA didn't protect those people.

**Comment by parabola949** [comment]
This MIGHT be fixed in e89663b

**Comment by renyhp** [comment]
Okay, closing this one. We'll wait for it to happen again
