### ISSUE TITLE
Two messages for Guardian Angel

### ISSUE THREAD

**Issue by michelleized** [parabola949/Werewolf#171]
Guardian Angel gets 2 messges 
1. you safed XXXs life
2. XXX wasn't attacked this night.
But between these two messages were no lynch time / voting. Messages were sent in the same night. Also, the person that the Guardian Angel was saving was attacked and saved.

**Comment by renyhp** [comment]
What was the role of that player?

**Comment by MatteoIlGrande** [comment]
@renyhp It happened to me when I was Prince
