### ISSUE TITLE
No werewolf and straight to win

### ISSUE THREAD

**Issue by kabag** [parabola949/Werewolf#176]
start chaos...role as attached

![image](https://cloud.githubusercontent.com/assets/22428223/20372010/e864fccc-ac9a-11e6-94ef-109166c8a740.png)

**Comment by parabola949** [comment]
@kabag We are aware, and fixing it soon

**Comment by renyhp** [comment]
Hopefully fixed with last commit... Reopen the issue if it happens again after the bot is updated.

**Comment by michelleized** [comment]
@renyhp @renyhp What does this do?

**Comment by joshkurien** [comment]
also, could you clarify as to whether to use Chaos or normal mode now ideally.

**Comment by renyhp** [comment]
@joshkurien Normal mode is balanced. The roles are chosen in a way that it is not too simple or too hard for the village to win. 
Chaos mode is just random, so you can expect anything from it. 
What to use is up to you, just choose your favorite mode :)

**Comment by kabag** [comment]
I want to be more balanced but in the same time all has roles.not just
plain lowly villager. So is it better to start chaos or start game?

**Comment by joshkurien** [comment]
@kabag so thats the point, now Normal games have all roles as well, not like it was before.
