### ISSUE TITLE
Suggestion: Make the game easier to follow with a simple update

### ISSUE THREAD

**Issue by NachoCozza** [parabola949/Werewolf#177]
Send only ONE message with the scoreboard, and update it when people start voting who to lynch
It makes the game easier for noob players by letting them decide in a smarter way who to lynch next

Player One 2️⃣/3️⃣
    Want to lynch 🔪:
        - Player Two
        - Player Three
Player Two 1️⃣/3️⃣ :
    Want to lynch 🔪:
        - Player One

**Comment by parabola949** [comment]
Problem with this, in large groups the conversation is usually going so fast, the message would be lost quickly.  Also, in large games, the messages (edits) would be over 512 bytes, and bots are only allowed to send a few of those a minute.  Doing this would cause the bot to hit API limits so fast not even SpaceX boosters could keep up
