### ISSUE TITLE
Problem with wolf assignment

### ISSUE THREAD

**Issue by renyhp** [parabola949/Werewolf#188]
### Problem
Werewolf.cs, line 997:
```c#
case IRole.WolfCub:
case IRole.AlphaWolf: //don't add more wolves, just replace
     rolesToAssign.Add(role);
     rolesToAssign.Remove(IRole.Wolf);
     break;
```
If `playerCount < 10`, before the block there was only one wolf, but these lines add both Wolf Cub and Alpha Wolf, resulting in games where `playerCount < 10` but there are 2 wolves.
Besides, these lines bring the secondary problem that, if `playerCount < 15`, the only normal wolves will be substituted. This results in no role list having normal wolves; although games still will be able to contain normal wolves (e.g. if the first `playerCount` roles contain a Traitor / Sorcerer but not a Wolf), those games will be very unlikely to happen.

### Possible solutions

Replacing those lines with
```c#
case IRole.WolfCub:
case IRole.AlphaWolf:
     if (rolesToAssign.Remove(IRole.Wolf))
          rolesToAssign.Add(role); 
```
won't help because, in games with less than 10 players, that would add only the Alpha Wolf (as `IRole.AlphaWolf < IRole.WolfCub`).

Two possible solutions follow. I'm not sure of either of the two, though.

**EDIT: I've made a PR with a possible better solution than those two.**

#### Solution 1: after getting the role list, check if there are too many wolves
Add these lines after line 1059:
```c#
//make sure we don't have too many wolves
while (rolesToAssign.Count(x => WolfRoles.Contains(x)) > count / 5)
{
    //substitute a random wolf with a random villager
    var wolf = rolesToAssign.FindIndex(x => WolfRoles.Contains(x)); //the random order will choose for us which one
    rolesToAssign[wolf] = Enum.GetValues(typeof(IRole)).Cast<IRole>().Where(x => !nonVgRoles.Contains(x) && !rolesToAssign.Contains(x)).DefaultIfEmpty(IRole.Villager).FirstOrDefault();
}
```
This would solve the main problem, but not the secondary one.

#### Solution 2: figure out a random algorithm to add Alpha and Cub only by chance
Delete the bugged lines, and add the following ones outside the `foreach` block:
```c#
if (rolesToAssign.Count(x => x == IRole.Wolf) < 3)
{
    //don't auto-replace, otherwise we (almost) won't have small games with normal wolves
    List<IRole> RemainingWolves = new List<IRole>{ IRole.AlphaWolf, IRole.WolfCub };
    for (var i = 0; i < 2; i++)
        if (Program.R.Next(100) < 50)
        {
            if (rolesToAssign.Remove(IRole.Wolf))
            {
                var index = Program.R.Next(RemainingWolves.Count());
                rolesToAssign.Add(RemainingWolves[index]);
                RemainingWolves.Remove(RemainingWolves[index]);
            }
        }
}
else
{
    //for large games, we don't need any random algorithm, because we still may have normal wolves
    if (rolesToAssign.Remove(IRole.Wolf))
        rolesToAssign.Add(IRole.AlphaWolf);
    if (rolesToAssign.Remove(IRole.Wolf))
        rolesToAssign.Add(IRole.WolfCub);
}
```
This random algorithm does not do any difference between Wolf Cub and Alpha Wolf, and adds each one of them only at 50% chance.

**Comment by joshkurien** [comment]
What was/is this issue?

**Comment by renyhp** [comment]
While I was writing, I figured out there exists an even better solution. I'll do a PR with it
