### ISSUE TITLE
Doppelganger auto lose if died untransformed

### ISSUE THREAD

**Issue by subyhussy** [parabola949/Werewolf#191]
Doppelganger should be classed as vg death by default if they the person died. Yes I get that they are untransformed so they don't technically have a team but their death is a auto lose which doesn't seem fair

**Comment by renyhp** [comment]
@subyhussy Why isn't it fair? The untransformed doppelganger's goal is make so that their role model dies, not to kill werewolves, cultists and SK (like VGs)

**Comment by SilasSit** [comment]
But WC?
