### ISSUE TITLE
Cultist dies twice when lynched + visited by CH the following night

### ISSUE THREAD

**Issue by ambravl** [parabola949/Werewolf#40]
During a game, a cultist was voted to be lynched. The CH voted on her, the bot accepted her choice, and the cultist was successfully lynched. Following that, when night came, an inline keyboard appeared for the CH, but she couldn't make any choices. Once night ended, the inline keyboard didn't disappear, but the bot answered CH saying she went to the (dead!) cultist's house and killed her. Following that, it sent a message in the group saying the (already dead!) cultist had been killed by the CH.

**Group ID:** -1001066860506
**Bot's messages:**
CH voting to lynch cultist:

> Werewolf Moderator, [05.07.16 04:23]
> Pratya has voted to lynch 천사 Angel
> 
> Belladonna has voted to lynch 천사 Angel
> 
> Käzúyä 戀柯 has voted to lynch 천사 Angel
> 
> Daredevil has voted to lynch Ghoul 👻

Bot accepting CH's choice:

> Pratya, [05.07.16 04:53]
> [Forwarded from Werewolf Moderator]
> Choice accepted - 천사 Angel

Cultist being lynched:

> Werewolf Moderator, [05.07.16 04:23]
> The villagers have cast their votes, amid doubts and suspicions. 천사 Angel is dead. 천사 Angel was a Cultist 👤
> 
> Night has fallen.  Everyone heads to bed, weary after another stressful day.  Night players: you have 90 seconds use your actions!

Bot telling CH she visited cultist's house:

> Pratya, [05.07.16 04:51]
> [Forwarded from Werewolf Moderator]
> Did something happen at 천사 Angel's house last night? You can't seem to remember...

Bot telling the group cultist died, again:

> Werewolf Moderator, [05.07.16 04:24]
> As everyone rises, they find the body of Ghoul 👻 shoved into a pile of stone, blood splattered everywhere. One of your masons has died!
> 
> A noticeable stench is coming from 천사 Angel's house...  the village inspects it to find a body lying in front of a dark altar...  a cultist has been killed by the hunter!
> 
> It is now day time.  All of you have 120 seconds to make your accusations / defenses / talk.
> 
> Day 3

Screenshot of bot's PM with CH:
![image](https://cloud.githubusercontent.com/assets/20179427/16578095/0bffc306-426f-11e6-964b-c73b377c975a.png)
![image](https://cloud.githubusercontent.com/assets/20179427/16578100/13bd456e-426f-11e6-8675-e819dc34d032.png)

**Comment by castaway2000** [comment]
working on this one.

**Comment by renyhp** [comment]
I'm closing this issue, because with update 4.0 a lot has changed, and this problem is likely to have been fixed. If this happens again, please do open another issue.
