### ISSUE TITLE
DG has useless "Skip" button

### ISSUE THREAD

**Issue by renyhp** [parabola949/Werewolf#42]
It is useless since, if they press it, the bot chooses randomly anyway.

Possible fixes: 
- Just delete it
- Make possible for DG to skip choice (although that's somehow against the "bot chooses randomly" logic)

**Comment by FirewoodLoki** [comment]
What if someone indecisive wants a random button?

**Comment by parabola949** [comment]
That's essentially what it is.  A "Choose for me" button.
