### ISSUE TITLE
7/7 & 8/7 added strings to be translate

### ISSUE THREAD

**Issue by FirewoodLoki** [parabola949/Werewolf#45]
Below messages should be translatable as well:

First problem is that, the translation of recently added message is not working.

Second, there two more strings needed to be translated:
1. 
"/AboutVG - Villager
/AboutSeer - Seer
/AboutWw - Werewolf..."

2.
the {0} in strings: AllowFleeQ and AllowFleeA

**Comment by DeiDo** [comment]
We need to translate {0} in ShowRolesDeathQ and ShowRolesDeathA as well as these strings up.

**Comment by renyhp** [comment]
@parabola949, as for the rolelist, we could make it become a new string itself... is that a good idea? If yes, i'll talk about it with pierre, and one of the two of us will do that and send the pull request

**Comment by renyhp** [comment]
1. #57: even if names are not translatable, there will be emojis, so that players can use those to understand roles
2. #58: Rewording AllowFlee strings to use "Allow"/"Disallow" strings.

Waiting for Para to merge, if he wants to.

**Comment by renyhp** [comment]
Solved via commits dc98c2c6db21e9cc50b44511e627900e81f3d57b and b2ab953aff2887143ed9fe044d5b006047f0ca4e.
