### ISSUE TITLE
Hunter unable to choose someone to shoot after they are lynched

### ISSUE THREAD

**Issue by Dabadooba** [parabola949/Werewolf#54]
Korosensei:
Each time i become a hunter and killed by sk or lynched, i cant choose another person to be dragged with me

Last time it happened was: 12:10 UTC +7 10 July 
Group Name: Werewolf Amnesia 
Group id: -1001066860506

**Comment by Dabadooba** [comment]
Screenshot is tagged #54 in support chat

**Comment by renyhp** [comment]
I'm closing this issue, because with update 4.0 a lot has changed, and this problem is likely to have been fixed. If this happens again, please do open another issue.
