### ISSUE TITLE
Unable to use inline buttons for a whole game

### ISSUE THREAD

**Issue by Dabadooba** [parabola949/Werewolf#55]
No one was able to use inline buttons to choose anyone during the night or day, including lynch vote. 

Time: 6:06 UTC 10 June
Group ID: -1001032697807

**Comment by Dabadooba** [comment]
/ping and /runinfo during the game forwarded to support chat and tagged #55

**Comment by parabola949** [comment]
This was related to issues with the nodes bugging out, which has been resolved
