### ISSUE TITLE
Bot chose lovers for cupid, but they didn't receive a message

### ISSUE THREAD

**Issue by ambravl** [parabola949/Werewolf#75]
On the group -1001052795980 (Combriccola WereWolfBot), August 13th at 20:34 GMT+2, bot 2 chose the lovers in place of the cupid, who didn't choose in time. The lovers chosen were the Seer and the Serial Killer, but neither received a message from the bot telling them they were lovers. The Seer had chosen the Serial Killer to see on the first night, and once day come (still with no message), they told the group, and got the Serial Killer lynched... Only then did he find out he was actually his lover.

**Screenshot from the Seer**
![image](https://cloud.githubusercontent.com/assets/20179427/17645016/360722f6-616f-11e6-918d-2432f9a4701c.png)

**Game's status in the end**
Werewolf Moderator 2, [13.08.16 15:38]
Giocatori in vita: 5\8
Tris: 💀 Morto - l'Artigliere🔫 Vinto
Fede Alfonso: 💀 Morto - il Serial Killer🔪❤️ Vinto
Aurelio Colombo: 💀 Morto - il Veggente👳 ❤️ Vinto
Alicetta¤: 🙂 In vita - il Veggente👳  Vinto
Sergio: 🙂 In vita - Il Cacciatore urbano🎯 Vinto
Tomodachi: 🙂 In vita - Cupido🏹 Vinto
Diego: 🙂 In vita - l'Investigatore🔎 Vinto
Leo145: 🙂 In vita - il Maledetto😾 Vinto

Durata della partita: 00:05:14

**Comment by renyhp** [comment]
I'm closing this issue, because with update 4.0 a lot has changed, and this problem is likely to have been fixed. If this happens again, please do open another issue.
