### ISSUE TITLE
Any plan build a Liunx / unix server version?

### ISSUE THREAD

**Issue by LOVEChen** [parabola949/Werewolf#79]
plzzzzzz

**Comment by CloneMMDDCVII** [comment]
@LOVEChen 1) It's not an issue
2) Nope, there is no unix version planned. However, one person did try to rewrite the bot to python but i can't remember who.

**Comment by parabola949** [comment]
If you can manage to make it run in on Linux, awesome, but it's .NET.  current DNX capabilities are not enough to code werewolf in it

**Comment by putuyoga** [comment]
@parabola949 : did you mean .NET Core ?

**Comment by parabola949** [comment]
@putuyoga That is what DNX means.....
