### ISSUE TITLE
What Visual studio version to use ?

### ISSUE THREAD

**Issue by groovecain** [parabola949/Werewolf#80]
I try to build an private server or something like that, i already set-up the Windows Server & SQL server, but when i open the solution with Visual Studio 2015 update 3 , it failed to load the solution/file ,

**Comment by CloneMMDDCVII** [comment]
@groovecain Can you give details on received error ?

**Comment by parabola949** [comment]
I am using VS2015 U3.  If you'd like to submit an issue, please provide some more information, like screenshots or error details.

**Comment by groovecain** [comment]
here the error 

E:\Project\wolf\Werewolf-master\Werewolf-master\Werewolf for Telegram\Werewolf Control\Werewolf Control.csproj : error  : Could not load file or assembly 'Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

E:\Project\wolf\Werewolf-master\Werewolf-master\Werewolf for Telegram\Werewolf Node\Werewolf Node.csproj : error  : Could not load file or assembly 'Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

E:\Project\wolf\Werewolf-master\Werewolf-master\Werewolf for Telegram\TcpFramework\TcpFramework.csproj : error  : Could not load file or assembly 'Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

E:\Project\wolf\Werewolf-master\Werewolf-master\Werewolf for Telegram\Database\Database.csproj : error  : Could not load file or assembly 'Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

E:\Project\wolf\Werewolf-master\Werewolf-master\Werewolf for Telegram\Updater\Updater.csproj : error  : Could not load file or assembly 'Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

E:\Project\wolf\Werewolf-master\Werewolf-master\Werewolf for Telegram\StatsRotation\StatsRotation.csproj : error  : Could not load file or assembly 'Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

**Comment by parabola949** [comment]
@groovecain You appear to have a corrupted installation of Visual Studio.  Repair it.

**Comment by groovecain** [comment]
@parabola949 i see, let me try repairing my vs first, thanks for you reply :smile:
