### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by jultj** [parabola949/Werewolf#81]
How to start a werewolf game in a private group? I want to play private games with my friends.. Pls help

**Comment by BlaQPhoeniX** [comment]
@jultj You can add it just like you would add a friend by their usernames (click Add Member and then type @werewolfIIbot into the search box), or you can go to the bot's profile by clicking its name and click 'Add to group'!

**Comment by CloneMMDDCVII** [comment]
@jultj How to play:

a. start a game

you can either join games big groups in /grouplist@werewolfbot
or
you can add @werewolfbot to your own groups and start the game in your groups with friends.

b. what is werewolf

Werewolf is a text based game where there is a village. Most of the people are villagers and some of them are werewolves. The game cycles through day and night. During the day the whole village votes to lynch someone and at night the werewolves choose someone to kill. The villagers win when all of the werewolves are dead. The werewolves win when there are more werewolves than villagers

**Comment by jultj** [comment]
Thx men
