### ISSUE TITLE
Changing Side Works achievement problem

### ISSUE THREAD

**Issue by jack980517** [parabola949/Werewolf#82]
I'm WW, linked to a Cursed by Cupid, bit that Cursed and won the game. However I got the Changing Side Works achievement.
I'm five hearts.

幸存者们: 3 / 6
Mudana: 💀死亡 - 孤儿👶 失败
『 人 は 、 障害 に 向き合っ た 時 、 自ら を 発見 する 』: 💀死亡 - 妓女💋 失败
xiaoguai: 💀死亡 - 杀人魔🔪 失败
Mason G: 🙂幸存 - 丘比特💘 失败
Stopttttttttttttttttt: 🙂幸存 - 狼人🐺❤️ 胜利
💙💚💛❤️💜: 🙂幸存 - 狼人🐺❤️ 胜利

游戏进行了：00:04:09

**Comment by parabola949** [comment]
Did the cursed get the achievement?

**Comment by jack980517** [comment]
Yes

**Comment by renyhp** [comment]
I'm closing this issue, because with update 4.0 a lot has changed, and this problem is likely to have been fixed. If this happens again, please do open another issue.
