### ISSUE TITLE
Project Telegram.Bot does not contain any commands

### ISSUE THREAD

**Issue by reegomes** [parabola949/Werewolf#84]
Para, 
I tried to run your bot but presented this [error](http://prntscr.com/c8ccbm)

Is there any way to fix
![Error](https://cloud.githubusercontent.com/assets/12734870/17834766/aaf0a108-6725-11e6-9fdd-6cb290b309b7.png)

**Comment by parabola949** [comment]
Uhhhhhh....   Telegram.Bot is a library.  It is definitely not werewolf bot.  So, no, you can't run a library.  Really.
