### ISSUE TITLE
[REQUEST] Dr Who Theme

### ISSUE THREAD

**Issue by LtCuzco** [parabola949/Werewolf#87]
I was wondering if there could be a theme for Dr Who? Ex: werewolf(or cultist) = cyberman.

**Comment by BladeZero** [comment]
@LtCuzco Yes there can be, do you want to write it?

**Comment by Valkeerie** [comment]
I have been contemplating this but don't the the character composition from Doctor Who is easily translatable to werewolves. What do you think @LtCuzco ?

**Comment by Valkeerie** [comment]
In the alternative, what do you think about a Star Wars theme?

**Comment by parabola949** [comment]
@Valkeerie Hey guys, if you wanna chat about it, come to @werewolfsupport

**Comment by Valkeerie** [comment]
@parabola949 ty - that was my first github comment so experimenting :) when @LtCuzco is my friend irl too, so when we get a few ideas, we'll bring them to support chat.

**Comment by renyhp** [comment]
I'm closing this issue because... it's something that developers won't do. It is totally possible to have this theme, we just need someone to write it. If someone wants to, they are completely welcome :) Please write on Werewolf's Telegram chats, hopefully you'll find some interested people there.
