### ISSUE TITLE
Werewolf or serial killer is on the last player list. Bug?

### ISSUE THREAD

**Issue by dinza** [parabola949/Werewolf#88]
Almost every game (may be >80%) i played, player on the last player list when game started is serial killer or werewolf. So it is easy to guess who the werewolf is.

**Comment by CloneMMDDCVII** [comment]
@dinza Then you are quite lucky ;) player list is random :p

**Comment by triesonyk** [comment]
yeah, it also happened on my group too
i hope they remove the auto-shown player list
