### ISSUE TITLE
Hunter killed at day time by SK displays wrong string

### ISSUE THREAD

**Issue by eagle3000** [parabola949/Werewolf#9]
When the hunter is killed at day time, the bot will always display the "HunterShotChoice" string even though it could also have been the SK.
There are two possible fixes: Introduce another string for hunter being killed by SK or change the exisiting string to cover kills by SK as well

**Comment by eagle3000** [comment]
This also applies to other scenariosm I think. Just checked and the hunter got killed at night by SK and the HunterNoChoiceShot string was displayed.

**Comment by renyhp** [comment]
This issue should be reopened. HunterNoChoiceShot, HunterSkipChoiceShot, and HunterKilledFinalShot are also displayed when Hunter is killed by SK, and they currently don't cover SK kills. At least, translators should know they have to fix it
