### ISSUE TITLE
Suggestion: When a player AFKs in main, only report the number of times they AFKed in main.

### ISSUE THREAD

**Issue by RainRat** [parabola949/Werewolf#96]
When a player is killed for AFK in main, the bot reports the number of AFKs in all groups. For admins of main, it only makes sense to take action on things that actually happen in main. So bot should report only AFKs that happened in main, when reporting number of AFKs in the past 24 hours.

**Comment by parabola949** [comment]
The point is to identify players that are habitually afk.  this includes players that hop groups and afk (basically, people just trying to get game count up by joining games on all three bots then walking away)
