### ISSUE TITLE
Werewolf enforcer stopped sending me notifications.

### ISSUE THREAD

**Issue by wafflesmama** [parabola949/Werewolf#98]
I have been admin of the group since the group started and everything was fine until 1 sep. I stopped receiving notifications from werewolf enforcer regarding all the reports (@admin) etc. But the bot still responds to me in any other way. I can still warn members etc. The only error is the reports. Please help solve the issue as I gotta help my other admins out! Thanks:)

**Comment by parabola949** [comment]
This issue is a problem with enforcer, not werewolf.  Please kindly submit your issue in enforcers repo, so the developer for it can take care of it.
https://github.com/dllz/GroupButler

**Comment by dllz** [comment]
@wafflesmama Lol this was meant to be in enforcers GitHub not ww GitHub

**Comment by wafflesmama** [comment]
Okay sorry thanks!!

**Comment by CloneMMDDCVII** [comment]
@wafflesmama Use /menu to open menu, and allow reports. Please do not respond here but on the enforcer's github or in @werewolfsupport
