### ISSUE TITLE
Random order for lynch and other buttons with names

### ISSUE THREAD

**Issue by bjaskj** [parabola949/Werewolf#99]
Currently the order of lynch and other action buttons with names are A-Z sorted, this makes it a HUGE disadvantage if you have a name that shows up high all the time.

Other games that have a voting system have many left out the first 1-3 choices if you select 0-9 keys on your keyboard or the have a randomly listed choices to avoid most people selecting the first option.

Currently the stats for a player who ends up on top of the button list is:
Most likely to die first night: 38%
Most likely to get lynched first day: 18%
Most likely to die first 24 hours: 57%

Please fix this balancing issue with the game, thanks! 👍

**Comment by parabola949** [comment]
@bjaskj I'll fix it tomorrow
